### ISSUE TITLE
Depth to Distance in meter

### ISSUE THREAD

**Issue by princemio** [ThomasLengeling/KinectPV2#19]
Hey i have a question.

i want to calculate the xyz position for a specific pixel in the image.
i already have the hole formula but i need to get the distance to the pixel from depth raw data. 

How does this :
int [] depthRaw = kinect.getRawDepth();

...relate to meter or distance...or how can i get the distance of a pixel in any way?

**Comment by ThomasLengeling** [comment]
hey sorry for the late response.
the raw depth is now working.

```getRawDepth``` return an array of ints, values from 0 - 4500 in mm

check out the branch

https://github.com/ThomasLengeling/KinectPV2/tree/0.7.3

**Comment by ThomasLengeling** [comment]
Fixed with 0.7.3
