### ISSUE TITLE
KinectPV2 java issues

### ISSUE THREAD

**Issue by Adiou** [ThomasLengeling/KinectPV2#22]
Hi, 
when I try  examples, i get "This version of Processing only supports libraries and JAR files compiled for Java 1.6 or earlier. A library used by this sketch was compiled for Java 1.7 or later, 
and needs to be recompiled to be compatible with Java 1.6."

I saw this already happend to somebody else. You provided him an other download link, it work for him, he doesn't for me...

I'm on windows 8.1, with the latest kinect sdk and processing 2.2.1.

Thanks for your help! 

Adrien

**Comment by ThomasLengeling** [comment]
hey!, try using the library with the latest processing 3.11a 

thomas

**Comment by Adiou** [comment]
Hey, thanks for your fast answer!
I tried, but I get a" illegalStateException : fullScreen() cannot be used here...."
I'm checking processing reference right now...
Adrien

**Comment by Adiou** [comment]
I change the size, but now I get error because I'm using 32bits version of processing 3...Downloading the 64bits versions...

**Comment by Adiou** [comment]
Tried it with 64bits version, still "illegalStateException : fullScreen() cannot be used here" pb, change the size, sketch running but I just get a black screen...

**Comment by Adiou** [comment]
It's working with processing 2.2.1 and the version 0.7.1...

**Comment by ThomasLengeling** [comment]
yeah is only for windows 8 64 bits, and the newest version of processing.

Sorry for the minor bugs of the examples, the new size() only works with static values, so change size(512*3, 424) to size(1536, 424).

I'll to try to make those fixes today.

Thomas

**Comment by Adiou** [comment]
Thanks for all Thomas!
Adrien

**Comment by Adiou** [comment]
Just a last thing : with processing 3 and the version 0.7.3 of the library, when I change the size, the sketch is running but I have nothing but a black screen with the frameRate...

**Comment by ThomasLengeling** [comment]
amm strange. any console output?

**Comment by Adiou** [comment]
Actually BodyTrack_User, DepthTest, HDColor,  HDFaceVertex, MapDepthToColor, Mask_findUsers, MaskTest, FindContours, LiveCamTest, PointCloudColor, PointCloudDepth, PointCloudOGL, RecordPointCloud, SimpleFaceTracking, Skeleton3d, skeletonColor, SkeletonMaskDepth and TestImage are actually working.

But for CoordinateMapperRGBDepth i get "the function "setCoordbkglmg(int[])" does not exist" (sketch is not running) and for HDFaceVertex the sketch is running but I just get a black screen, no console output.

**Comment by ThomasLengeling** [comment]
hey the CoordinateMapperRGBDepth  is not working use 0.7.2, the HDFaceVertex should be working, takes some time in finding the user, or you should be close to the kinect/

**Comment by Adiou** [comment]
Yeap, you're right ;-)

**Comment by ThomasLengeling** [comment]
updated readme
