### ISSUE TITLE
faceHD vertex crashes

### ISSUE THREAD

**Issue by dfamil** [ThomasLengeling/KinectPV2#23]
facehd vertex crashes kinect goes on and than screen opens blank and than crashes.

**Comment by ThomasLengeling** [comment]
is there any console output?, does the other examples work?

**Comment by dfamil** [comment]
skeleton worked great i don't think any showed up in console before it quit.

**Comment by ThomasLengeling** [comment]
the should a be a console output, what is your OS?

**Comment by dfamil** [comment]
hi
i was using a prototype kinectv2 and i think a b1 of processing 3 i switch to a regular kinectv2 and  processing b3 that came out 2 days ago everything seems to be working. 

great library!!
