### ISSUE TITLE
DirectX 11 requirement

### ISSUE THREAD

**Issue by Lachie9383** [ThomasLengeling/KinectPV2#24]
I think it would be worth adding DirectX 11 to list of requirements in the README. 

I attempted to use the library on Parallels Desktop for Mac and ran into problems as it only supported DirectX 10. The console told me it had connected to the device but I wasn't getting any data. This can be worked around using Bootcamp which supports DirectX 11, but I think it would helpful to make this distinction clear so people don't repeat what I did in the future. 

Love the library! Keep up the great work.

**Comment by ThomasLengeling** [comment]
thanks you for point that out, going to add to the issues/requeriments.

thomas
