### ISSUE TITLE
open gl error with procsssing v.b4

### ISSUE THREAD

**Issue by dfamil** [ThomasLengeling/KinectPV2#26]
i imagined this not your problem but thought you should know in case they made a change with opengl in v.b4

. the shader example work fine in v.b3 but got a open gl function pgl.vertexAtrribPointer() error with v.b4

**Comment by ThomasLengeling** [comment]
ok, going to look in to it, thanks!

**Comment by ThomasLengeling** [comment]
what is the error, console output with pgl.vertexAtrribPointer() ?

**Comment by e1e8** [comment]
b5 showing what is likely to be the same error:
The function "vertexAttribPointer()" expects parameters like: "vertexAttribPointer(int, int, int, boolean, int, int)"

**Comment by ThomasLengeling** [comment]
i just updated the point cloud examples, so masters should be working
