### ISSUE TITLE
vertexAttribPointer()

### ISSUE THREAD

**Issue by dhawgood** [ThomasLengeling/KinectPV2#29]
Hi, I keep on getting a number of errors whilst trying to run Record Point Cloud. I've attached a screen grab in case it's of help?

![capture](https://cloud.githubusercontent.com/assets/14078760/9611855/f80410be-50d9-11e5-8445-a742cc999ce0.PNG)

**Comment by ThomasLengeling** [comment]
The new processing b5 and b4 introduced new a new openGL format, The examples need to be updated using the new features.

**Comment by ThomasLengeling** [comment]
Hey, I updated the library if you are interested, the point cloud examples are working, please try them out, soon ill package the lib soon to be able to download it from processing's CM.

**Comment by dhawgood** [comment]
thanks, it seems to be up and working again!
