### ISSUE TITLE
Get HDFace data from cameraspacepoint  

### ISSUE THREAD

**Issue by mjsyam** [ThomasLengeling/KinectPV2#32]
is there any way to get Get HDFace data from cameraspacepoint? so the unit will become cm.
Thanks

**Comment by ThomasLengeling** [comment]
hello mjsyam.
The cameraspacepoint function is not implemented in the library, Ill try to add it soon

**Comment by mjsyam** [comment]
Thanks Thomas. Is possible to modify the file on "KinectPV2_vc2012" project? I tried to bulid it, but i'm getting error.

**Comment by mjsyam** [comment]
Thanks Thomas. Is possible to modify the file on "KinectPV2_vc2012" project? I tried to build it, but i'm getting error.

**Comment by ThomasLengeling** [comment]
what is the error?
