### ISSUE TITLE
Compatible with 3.0.1?

### ISSUE THREAD

**Issue by shiffman** [ThomasLengeling/KinectPV2#34]
I'm seeing this library grayed out in the contributions manager on Processing 3.0.1 on a windows machine.  I believe it is compatible.  Perhaps the library.properties file has incorrect min / max versions in it?  cc @prisonerjohn.

**Comment by prisonerjohn** [comment]
Indeed the revision numbers were wrong in the contribs.txt file, I just updated it and it seems to work.
