### ISSUE TITLE
Processing contribution manager issue

### ISSUE THREAD

**Issue by brianhewitt** [ThomasLengeling/KinectPV2#41]
I seem to be having an issue with the library through the contribution manager in processing -- I get an error when I try to add the library through that interface. If I download the library and place the files in the libraries folder, it tells me there's an update available, but updating fails.

The documentation/readme  says you're at version 0.7.7, but the library.properties file says:
`prettyVersion = 0.7.6min`

Does that just need to be updated?

(sketches DO still run without problems)

**Comment by ThomasLengeling** [comment]
fixed thank you

**Comment by wtybee** [comment]
not  update
