### ISSUE TITLE
mapDepthToColor example doesn't show aligned image after version 0.7.2

### ISSUE THREAD

**Issue by rpugliese** [ThomasLengeling/KinectPV2#42]
Hello, I am having this strange issue. The example mapDepthToColor runs in all the versions but it does not show the depthToColorImg for version after 0.7.2.

![mapdepthtocolor](https://cloud.githubusercontent.com/assets/1745524/13391515/89fe731a-dedd-11e5-9222-ba36f9d4c0bb.PNG)

Thanks for the library and your help.

**Comment by ftqtfff** [comment]
I have the same problem.

**Comment by ThomasLengeling** [comment]
just fixed
