### ISSUE TITLE
exe file doesn't work

### ISSUE THREAD

**Issue by NicoleLu3** [ThomasLengeling/KinectPV2#46]
Hi Thomas,
your library is useful,but I found that when I export the sketch as application,the exe file  doesn't work. Other sketch working without kinect can work well. maybe when I export , as your kinect library is external, it's hard to implement it in the exe file ?  

Thanks，
Nicole

**Comment by ThomasLengeling** [comment]
mm, have tried coping the .dll files to the same folder where the .exe is?
All of them should be located in the lib folder. 

Also, ss there any error msg?

thomas

**Comment by NicoleLu3** [comment]
thanks for your answer,it works.
