### ISSUE TITLE
Issues with vertexAttribPointer() - none of the pointcloud examples are working

### ISSUE THREAD

**Issue by paraclete-pizza** [ThomasLengeling/KinectPV2#48]
Whenever I try to run any of the point cloud examples in the library, I get the following error:

`The function "vertexAttribPointer()" expects parameters like: "vertexAttribPointer(int, int, int, boolean, int, int)"`

Related to these lines of code:
```
  pgl.vertexAttribPointer(vertLoc, 3, PGL.FLOAT, false, 0, pointCloudBuffer);
  pgl.vertexAttribPointer(colorLoc, 3, PGL.FLOAT, false, 0, colorBuffer);
```

I've tried looking through the KinectPV2 Reference, but cannot find the functions involved, and am at a bit of a loss as to what to do.

**Comment by paraclete-pizza** [comment]
The issue seems to be with pointCloudBuffer and colorBuffer, neither of which are 'int' values.

I tried appending '.arrayOffset()' to the end of each, which should return an int, and (I thought) provide the 'offset' value vertexAttribPointer is looking for. However, while this allowed the program to compile, I got a runtime error:

`unsuportedOperationException
`

**Comment by ThomasLengeling** [comment]
are you still having problems with the openGL examples?

**Comment by paraclete-pizza** [comment]
Since I updated from 0.7.5 to 0.7.7, the OpenGL point cloud examples both work fine!
