### ISSUE TITLE
Color to Pointcloud

### ISSUE THREAD

**Issue by princemio** [ThomasLengeling/KinectPV2#8]
Is there any possibility to get the rgb image mapped to the depth image or vice versa?

this would enable chessboard calibration methods with projectors... i think with the old kinect this function was called context.alternativeViewPointDepthToImage() in simpleopenni example called AlternativeViewpoint3d.

it enabled us to analyse the rgb image for features (like a chessboard) and find the corresponding points in the XYZ map (or floatbuffer).

so far i think this feature is already implemented but you can only use it with mask like skeleton or user.

**Comment by oreo329** [comment]
i am having the same problem that color-to-depth(not depth to color in KinectPV2) is essential but missing in KinectPV2 for projector-kinect alignment. 

is it just an inverse relationship? 
is using the depth-to-color to generate color-to-depth possible to do?

**Comment by oreo329** [comment]
it is from MapDepthToColor from KinectPV2

 **float [] mapDCT = kinect.getMapDepthToColor();**

  //get the raw data from depth and color
  int [] colorRaw = kinect.getRawColor();

  //clean de pixels
  PApplet.arrayCopy(depthZero, depthToColorImg.pixels);

  int count = 0;
  depthToColorImg.loadPixels();
  for (int i = 0; i < KinectPV2.WIDTHDepth; i++) {
    for (int j = 0; j < KinectPV2.HEIGHTDepth; j++) {

      //incoming pixels 512 x 424 with position in 1920 x 1080
      **float valX = mapDCT[count * 2 + 0];
      float valY = mapDCT[count * 2 + 1];**

is there any way to use inverse mapping of DCT???
